---
title: "R重要数据分析函数"
author: 
- affiliation: Dongbei University of Finance & Economics
  name: Studennt. LJJ
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: tango
    theme: sandstone
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 5
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.show = "hold",
                      fig.align = "center",
                      tidy = FALSE)
```

## 加载经常用的R包

```{r,warning=FALSE,message=FALSE}
library(pacman)
# 模型
p_load(tidyverse,grf,glmnet,caret,tidytext,fpp2,
       forecast,car,tseries,hdm,tidymodels,broom)

# 读数据
p_load(readxl,writexl,data.table,openxlsx,haven,rvest)

# 数据探索
p_load(DT,skimr,DataExplorer,explore,vtable,stringr,lubridate)

# 可视化
p_load(patchwork,ggrepel,ggcorrplot,gghighlight,ggthemes,shiny)

# 其它常用包
p_load(magrittr,listviewer,devtools,here,janitor,reticulate,jsonlite)
```

## 数据分析函数

本节介绍的数据分析函数仅为入门所用，并且进行简单的数据分析足够，但是要深入学习R的数据分析，并且学习R语言最新的知识，则必须看R数据科学和高级R（第二版）这两本书，每本书刷两遍，基本能够处理与数据相关90%的工作量。最后若想学习python，你会发现python也是如此简单！（R和python处理数据都很强大！）

```{r}
# 显示加载到内存中的变量和函数名称
ls()

# 显示加载到内存中的变量和函数的详细信息
# ls.str()

# 计算返回向量中最大、最小的元素的索引值
x <- 1:100
print(which.max(x))
print(which.min(x))

# 如果向量中存在多个相等的最大、最小值返回的是第一个最大、最小值的索引
x <- c(1,2,5,2,1,5)
print(which.max(x))
print(which.min(x))

# 返回最大、最小值
print(max(x))
print(min(x))
```

```{r}
# 对向量进行排序，默认采用升序排序方式
x <- c(3,5,2,8,6,9,7,4)
print(sort(x))
print(sort(x,decreasing=T))   # 默认的降序参数设置为F，如果设置为T则采用降序排序
```

```{r}
# 日期字符串向量
t <- ymd("2014-1-1",
              "2014-3-1",
              "2014-3-18",
              "2014-2-14",
              "2014-4-26",
              "2014-4-1",
              "2014-1-24")
# 注意：R语言中很多函数都可以使用向量做参数
# sort()函数可以对日期序列做排序操作
t <- sort(t);print(t)
```

```{r}
# rev()函数对向量做逆序处理
x <- c(3,5,2,8,6,9,7,4)
print(x);print(rev(x))

# 上例中的日期型数据同样可以逆序排列
print(t);print(rev(t))
```

```{r}
# 获取游程的信息
x <- c(1,-1,1,1,1,-1,-1,1,1,1,1,1,1,1)
y <- rle(x)
x
y
print(mode(y))
str(y)
```

```{r}
# 按照大小对向量数据做分类处理，可以用于绘制直方图
x <- rnorm(n=10,mean=10,5)
print(x)
breaks <- c(-20,-10,0,10,20)   # 分割数据的边界数值向量
y <- cut(x,breaks)
y
print(summary(y))
```

```{r}
# 在向量中查找指定数据（数据可用向量形式给出）,此函数返回一个和原向量等长的向量
# 存在待匹配数据的位置上标记为N(第N个待匹配数据就标记N)
x <- c(2,5,1,4,6,4,3)
print(match(x,4))
print(match(x,c(4,5)))
```

```{r}
# 计算组合数/排列数
print(choose(5,2))
print(factorial(3))

# 符号函数
# 每日股市上涨下跌收益率有正有负可以用sign()函数生成1,-1,0组成的游程序列
cat("sign()函数运算结果：",sign(0),",",sign(3.14159),",",sign(-1024),sep="")
```

```{r}
# 删除向量、矩阵、数据框中的NA值
x <- c(1,2,NA,4,5,NA,7,6,8,9)

y <- na.omit(x);print(y);
print(length(y));print(class(y))

dim(x) <- c(5,2)
print(x)
print(na.omit(x)) # 删除数组中的NA值的规则是删除含有NA值的整行数据
```

```{r}
# 交易品的历史数据中可能存在NA数值，使用na.omit()函数将会删除整条历史记录

# 检测向量、矩阵、数据框中是否包含NA数值，如果包含返回错误信息
x <- c(1,2,NA,4,5,NA,7,6,8,9)
y <- na.omit(x)
x;y
# na.fail(x)
na.fail(y)

dim(x) <- c(2,5)
# na.fail(x)


# 去除向量中的重复数据
x <- c(1,2,NA,2,5,NA,4,3,4,9)
print(unique(x))
```

```{r}
# filter()从数据框中取出满足条件的子集
# 对于历史行情数据、历史交易记录可以很方便的取出其中感兴趣的数据
data(airquality)
head(airquality)
airquality %>% 
  filter(Temp > 80,Month == 5) %>% 
  select(Ozone:Day)
```




