---
title: "xts-处理高频时间序列数据"
# subtitle: "Lecture title"
author: 
- affiliation: Dongbei University of Finance & Economics
  name: Studennt. LJJ
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: haddock
    # code_folding: show
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: true
    keep_md: false
    keep_tex: false 
---

## 加载经常用的R包

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.show = "hold",
                      fig.align = "center",
                      tidy = FALSE)
```

```{r,warning=TRUE,message=FALSE}
library(pacman)
# 读数据
p_load(readxl,writexl,data.table,openxlsx,haven,rvest)
```

```{r,warning=TRUE,message=FALSE}
# 数据探索
p_load(tidyverse,DT,skimr,DataExplorer,explore,vtable,stringr,lubridate)
```

```{r,eval=TRUE,warning=FALSE,message=FALSE}
# 模型
p_load(tidyverse,grf,glmnet,caret,tidytext,fpp2,forecast,car,tseries,hdm,tidymodels,broom)
```

```{r,eval=TRUE,warning=FALSE,message=FALSE}
# 可视化
p_load(patchwork,ggrepel,ggcorrplot,gghighlight,ggthemes,shiny)
```

```{r,eval=TRUE,warning=FALSE,message=FALSE}
# 其它常用包
p_load(magrittr,listviewer,devtools,here,janitor,reticulate,jsonlite)
```

```{r}
p_load(printr,xts)
```

## xts包

```{r}
data("sample_matrix",package = "xts")
sample_matrix %>% datatable()
```

```{r}
sample_matrix %>% class()
```

```{r}
matrix_xts <- as.xts(sample_matrix,dateFormat = "Date")
matrix_xts %>% datatable()
matrix_xts %>% class()
```

```{r}
xts(1:10,Sys.Date() + 1:10)
xts(1:10,Sys.Date() + 1:10) %>% class()
```

## 提取数据

```{r}
matrix_xts %>% head()
```

提取一个特定的日期

```{r}
matrix_xts["2007-01-02"]
```

提取整个三月份

```{r}
matrix_xts["2007-03"]
```

提取2007年数据

```{r}
matrix_xts["2007"]
```

提取到指定数据

```{r}
matrix_xts["/2007-01-07"]
```

提取2007年6月25日至最后的所有数据

```{r}
matrix_xts["2007-06-25/"]
```

提取2007年5月28日至6月2日的数据

```{r}
matrix_xts["2007-05-28/2007-06-02"]
```

## 绘图

```{r}
sample_matrix %>% datatable()
sample_matrix %>% colnames()
sample_matrix %>% rownames()
```

```{r}
data <- sample_matrix %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "date") %>% 
  mutate(date = lubridate::ymd(date))
data %>% datatable()
```

```{r}
data %>% 
  ggplot(aes(x = date,y = Open)) +
  geom_point() +
  geom_line() +
  scale_x_date(date_breaks = "1 month") +
  theme(text = element_text(family = "Times New Roman"),
        axis.text.x = element_text(angle = 45,vjust = 0.8)) -> p1

data %>% 
  ggplot(aes(x = date,y = High)) +
  geom_point() +
  geom_line() +
  scale_x_date(date_breaks = "1 month") +
  theme(text = element_text(family = "Times New Roman"),
        axis.text.x = element_text(angle = 45,vjust = 0.8)) -> p2


data %>% 
  ggplot(aes(x = date,y = Low)) +
  geom_point() +
  geom_line() +
  scale_x_date(date_breaks = "1 month") +
  theme(text = element_text(family = "Times New Roman"),
        axis.text.x = element_text(angle = 45,vjust = 0.8))  -> p3

data %>% 
  ggplot(aes(x = date,y = Close)) +
  geom_point() +
  geom_line() +
  scale_x_date(date_breaks = "1 month") +
  theme(text = element_text(family = "Times New Roman"),
        axis.text.x = element_text(angle = 45,vjust = 0.8)) ->p4

(p1 + p2) / (p3 + p4)
```

```{r}
data %>% 
  tidyr::pivot_longer(cols = -date,names_to = "variable",values_to = "value") %>% 
  ggplot(aes(x = date,y = value,col = variable)) +
  geom_line() +
  geom_point() +
  facet_wrap(~variable,nrow = 2) +
  scale_x_date(date_breaks = "1 month",date_labels = "%Y-%m") +
  theme(text = element_text(family = "Times New Roman"),
        axis.text.x = element_text(angle = 30))
```

## 做一个ARIMA预测

```{r}
data_ts <- AirPassengers %>% as.xts()
data_ts %>% class()
data_ts %>% head()
```

```{r}
arima_fit <- auto.arima(data_ts,d = 1,seasonal = TRUE,max.p = 1,max.q = 1)
arima_fit %>% forecast::autoplot()
arima_fit %>% forecast::checkresiduals()
```















