---
title: "python数据分析第四周教程"
author: "ljj"
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: espresso
    theme: yeti
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      results = "hold",
                      fig.show = "hold",
                      fig.align = "center",
                      tidy = FALSE)
```

## 加载经常用的R包

```{r,warning=FALSE,message=FALSE}
library(pacman)
p_load(tidyverse,stringr,DT,skimr,DataExplorer,grf,glmnet,caret,tidytext,
       explore,patchwork,ggrepel,ggcorrplot,gghighlight,ggthemes,fpp2,
       forecast,magrittr,readxl,writexl,listviewer,car,tseries,vtable)
library(reticulate)
```

```{r}
py_config()
reticulate::py_available()
# reticulate::repl_python()
```

## 通用函数

```{python}
1 + 1
```

```{python}
import numpy as np
arr = np.arange(10)
print(arr)
arr.shape
np.sqrt(arr)
np.exp(arr)

x = np.random.randn(10)
y = np.random.randn(10)
x
y
```

```{python}
np.maximum(x,y)
```

```{python}
arr = np.random.randn(10)
print(arr)
np.modf(arr)
```

## 利用数组进行数据处理

```{python}
points = np.arange(-5,5,0.01)
points.shape
xs,ys = np.meshgrid(points,points)
ys.shape
ys
```

```{python}
import matplotlib.pyplot as plt
z = np.sqrt(xs**2 + ys **2)
z.shape

plt.imshow(z,cmap = plt.cm.gray)
plt.colorbar()
plt.title('image plot of $\sqrt{x^2 + y ^2}$ for a grid of values')

plt.draw()
```

```{python}
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

result = np.where(cond,xarr,yarr)
result
```

```{python}
x = np.arange(36).reshape(6,6)
x
np.where(x > 10,0,x)
```

## 数学与统计方法

```{python}
arr = np.random.randn(5,4)
arr

arr.sum(axis=0)
arr.sum(axis=1)
```

```{python}
arr
arr.mean(axis=0)
arr.mean(axis=1)
```

```{python}
arr = np.array([
  [0,1,2],
  [3,4,5],
  [6,7,8]
])
arr

arr.cumsum(axis=0)
arr.cumsum(axis=1)
arr.cumprod(axis=0)
arr.cumprod(axis=1)
```

## 布尔型数组

```{python}
arr = np.random.randn(100)
arr[0:10]
np.sum(arr > 0)
(arr > 0).sum()
```


```{python}
bools = np.array([False,True,False])
bools.any()
bools.all()


np.any(bools)
np.all(bools)
```

## 排序

```{python}
arr = np.random.randn(10)
arr
np.sort(arr)

arr.sort()  # vary!
arr
```

```{python}
arr = np.random.randn(5,3)
arr

np.sort(arr,axis = 0) # not vary
arr

arr.sort(axis=0)  # vary
arr
```

```{python}
large_arr = np.random.randn(1000)
large_arr[0:10]
large_arr.shape
large_arr.sort()
large_arr[0:10]         
```

## 唯一化以及其他的逻辑集合

```{python}
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names
print(names)

np.unique(names)

ints = np.array([3,3,3,2,2,1,1,4,5])
ints
np.unique(ints).dtype
```

```{python}
set(names)
sorted(set(names))
names
np.sort(names)
```

```{python}
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
np.in1d(arr,[10,2,5]).shape
```

## 线性代数

```{python}
x = np.arange(6).reshape(2,3)
x
y = np.arange(6).reshape(3,2)
y
x.dot(y)
x
y
```

```{python}
np.dot(x,y)
np.ones(3)

np.dot(x,np.ones(3))  # 2 * 1
np.dot(x,np.ones(3)).shape  # NB
```

```{python}
np.random.seed(12345)
X = np.random.randn(5,5)
X

mat = X.T.dot(X)
mat

np.linalg.inv(mat)
```

```{python}
np.linalg.inv(X).dot(X)
```

```{python}
q,r = np.linalg.qr(mat)
q;r
```

```{python}
mat
np.diag(mat)
np.diag(mat).shape
np.dot(mat,np.linalg.inv(mat))
np.trace(mat)
np.linalg.det(mat)
```

```{python}
A = np.random.rand(25).reshape(5,5)
A
b = A.sum(axis=1)
b
x = np.linalg.solve(A,b)
x
```

```{python}
# Check that the solution is correct:
 
np.allclose(np.dot(A, x), b)
```

```{python}
X = np.random.randn(100).reshape(20,5)
X.shape

Y = X.sum(axis=1)
Y

np.linalg.lstsq(X,Y)
```

```{python}
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
x
y
np.vstack([x,y])
np.row_stack([x,y])
np.column_stack([x,y])
# By examining the coefficients, we see that the line should have a
# gradient of roughly 1 and cut the y-axis at, more or less, -1.
 
# We can rewrite the line equation as ``y = Ap``, where ``A = [[x 1]]``
# and ``p = [[m], [c]]``.  Now use `lstsq` to solve for `p`:
# np.ones(len(x))
np.vstack([x, np.ones(len(x))]).shape
np.hstack([x,np.ones(len(x))])
A = np.vstack([x, np.ones(len(x))]).T

A 
m, c = np.linalg.lstsq(A, y, rcond=None)[0]
m, c
```

## 随机数生成

```{python}
samples = np.random.normal(size = (4,4))
samples
```

## 随机漫步

```{python}
import random
position = 0
walk = [position]
walk
steps = 1000
for i in range(steps):
    step = i if random.randint(0,1) else -1
    position = position + steps
    walk.append(position)
    
position
```

## 利用numpy进行历史股价分析

### 读入文件

```{python}
c,v = np.loadtxt("D:/RBookLearning/Data-Science-and-Economics/Python/data/data.csv",
    delimiter=",",
    usecols=(6,7),
    unpack=True)
c
v
```

```{python}
np.arange(1, 11)
np.arange(10, 0, -1)
np.average(np.arange(1, 11), weights=np.arange(10, 0, -1))
vwap = np.average(c,weights=v)
print(vwap)
```

```{python}
np.mean(c)

t = np.arange(len(c))
t

np.average(c,weights = t)
```

### 最高价和最低价

```{python}
h,l = np.loadtxt(fname="D:/RBookLearning/Data-Science-and-Economics/Python/data/data.csv",
delimiter=',',usecols=(4,5),unpack=True)
```

```{python}
h 
l
h.max()
l.max()
l.min()


print('spread high price:',np.ptp(h))
print('spread lower price:',np.ptp(l))
```

### 统计分析

```{python}
h.ptp()
h.max()
h.min()

c
np.median(c)
np.msort(c)
np.sort(c)

np.var(c)
```

```{python}
np.mean((c - np.mean(c))**2)
```

### 股票收益率

```{python}
c.shape
c[:-1]
np.diff(c)
returns = np.diff(c)/c[-1]
returns.std()

returns

np.diff(np.log(c))
```

```{python}
np.where(np.arange(10)>0)
np.where(returns > 0)
```

```{python}
logreturns = np.diff(np.log(c))
logreturns.shape
logreturns
```

```{python}
annual_volatility = np.std(logreturns)/np.mean(logreturns)
annual_volatility

annual_volatility = annual_volatility/np.sqrt(1./252.)
annual_volatility

monthly_volatility = annual_volatility * np.sqrt(1./12.)
monthly_volatility
```

### 日期分析

```{python,eval = FALSE}
from datetime import datetime

def datestr2num(s):
    return datetime.strftime(s,'%d-%m-%Y').date().weekday()

dates,close = np.loadtxt(fname="D:/RBookLearning/Data-Science-and-Economics/Python/data/data.csv",delimiter=",",usecols=c(1,6),converters={1:datestr2num},unpack=True)
```


```{python}
def datestr2num(s):
   return datetime.strptime(s, "%d-%m-%Y").date().weekday()
```


```{python}
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x
np.split(x,3,axis = 1)
# np.take()
a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)

```

### 真实波动幅度均值

```{python}
h, l, c = np.loadtxt('D:/RBookLearning/Data-Science-and-Economics/Python/data/data.csv', delimiter=',', usecols=(4, 5, 6), unpack=True)
h
l
c
```

```{python}
len(c)
c[-2:-1]
N = 20
h = h[-N:]
h
l = l[-N:]
```

```{python}
len(h)
len(l)
c

previousclose = c[-N-1:-1]
previousclose

len(previousclose)

truerange = np.maximum(h - l,h - previousclose, previousclose - l)
truerange
```

```{python}
atr = np.zeros(N)
atr
len(atr)
for i in range(1,N):
    atr[i] = (N - 1) * atr[i - 1] + truerange[i]
    atr[i]/=N
    
atr
```

## 第五周


























