---
title: "purrr官方教程笔记"
author: "LJJ"
date: "2020/4/21"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.align = "center",fig.show = "hold")
```

## 一个简单例子

```{r}
mtcars %>% 
  split(.$cyl) %>% 
  map(function(x){lm(mpg ~ wt,data = x)}) %>% 
  map(summary) %>% 
  map_dbl("r.squared")
```

## 对列表或原子向量的每个元素应用一个函数

```{r}
1:10 %>% 
  map(rnorm,n = 10)

1:10 %>% 
  map(~rnorm(10,mean = .x))  

```

```{r}
1:10 %>% 
  map(function(x){
    rnorm(10,x)
  })     # 匿名函数
```

```{r}
1:10 %>% 
  map(function(x){
    rnorm(10000,x)
  }) %>% 
  map(mean)
```

```{r}
1:10 %>% 
  map(function(x){
    rnorm(10000,x)
  }) %>% 
  map_dbl(mean)
```

```{r}
favorite_desserts <- list(Sophia = "banana bread", Eliott = "pancakes", Karina = "chocolate cake")
favorite_desserts
```

```{r}
favorite_desserts %>% 
  map_chr(~paste(.,"rocks!"))
```

```{r}
l1 <- list(list(a = 1L), list(a = NULL, b = 2L), list(b = 3L))
l1
l1 %>% 
  map(2)
```

```{r}
l1 %>% map_int("b", .default = NA)
```

```{r}
l1 %>% map_int(2, .default = NA)
```

```{r}
l2 <- list(
  list(num = 1:3,     letters[1:3]),
  list(num = 101:103, letters[4:6]),
  list()
)
l2 %>% 
  map(c(2,2))
```

```{r}
l2 %>% map(list("num", 3))
```

```{r}
mtcars %>% 
  map(sum)   # dataframe的元素是列
mtcars %>% 
  map_dbl(sum)
```

```{r}
mtcars %>% 
  split(.$cyl) %>% 
  map(~lm(mpg~wt,data = .)) %>% 
  map(broom::tidy)
```

## 同时映射多个输入

```{r}
x <- list(1, 1, 1)
y <- list(10, 20, 30)
z <- list(100, 200, 300)
x
```

求和

```{r}
map2(x,y,function(x,y){
  x + y                    # 对应元素相加
})
```

```{r}
pmap(list(x, y ,z),sum)
```

按位置匹配参数

```{r}
pmap(list(x,y,z),function(first,second,third){
  (first + second) * third
})
```

按名称匹配参数

```{r}
pmap(list(a = x,b = y,c = z),function(c,b,a){a+c}*b)
```

The "p" for "parallel" in pmap() is the same as in base::pmin()

```{r}
df <- data.frame(
  x = c(1, 2, 5),
  y = c(5, 4, 8)
)

pmin(df$x,df$y)
```
