---
title: "R语言技巧"
# subtitle: "Lecture title"
author: 
- affiliation: Dongbei University of Finance & Economics
  name: Studennt. LJJ
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    highlight: haddock
    # code_folding: show
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: true
    keep_md: false
    keep_tex: false 
---

## 加载经常用的R包

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.show = "hold",
                      fig.align = "center",
                      tidy = FALSE)
```

```{r,warning=FALSE,message=FALSE}
library(pacman)
# 读数据
p_load(readxl,writexl,data.table,openxlsx,haven,rvest)
```

```{r,warning=FALSE,message=FALSE}
# 数据探索
p_load(tidyverse,DT,skimr,DataExplorer,explore,vtable,stringr,lubridate)
```

```{r,eval=FALSE,warning=FALSE,message=FALSE}
# 模型
p_load(tidyverse,grf,glmnet,caret,tidytext,fpp2,forecast,car,tseries,hdm,tidymodels,broom)
```

```{r,eval=FALSE,warning=FALSE,message=FALSE}
# 可视化
p_load(patchwork,ggrepel,ggcorrplot,gghighlight,ggthemes,shiny)
```

```{r,eval=FALSE,warning=FALSE,message=FALSE}
# 其它常用包
p_load(magrittr,listviewer,devtools,here,janitor,reticulate,jsonlite)
```

## [如何设置%in%快捷键](http://rstudio.github.io/rstudioaddins/#overview)

```
devtools::install_github("rstudio/addinexamples", type = "source")
```

安装完这个软件包后，你应该看到Addins工具栏菜单中填充了这个软件包导出的Addins:当然，最好是通过**快捷键插入%in%**，而不是通过点击菜单，所以让我们来学习如何将这个插件绑定到快捷键。首先，单击**BrowseAddins...**浏览当前可用的所有Addins。在对话框的左下角，你会看到键盘快捷键...按钮。单击此处，修改键盘快捷方式小部件将被打开，并过滤到当前的 addins 集。让我们将Insert% In% 绑定到**Ctrl + Alt + Shift + k**

## 重要快捷键
































