---
title: "Tidyverse中10个技巧性函数-来源YouTube"
author: "LJJ"
date: "2020/4/17"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.align = "center",fig.show = "hold")
```

## count

```{r}
library(tidyverse,warn.conflicts = FALSE)
library(DT)
library(lubridate)
```

```{r}
ggplot2movies::movies %>%
  group_by(year) %>%
  count(sort = FALSE, name = "num") %>%
  mutate(decade = 10 * (year %/% 10)) %>%
  ungroup() %>%
  select(-year) %>%
  group_by(decade) %>%
  summarise(n = sum(num)) %>%
  ggplot(aes(decade, n)) +
  geom_col(aes(decade, n)) +
  scale_x_continuous(breaks = seq(1890, 2000, 10)) +
  scale_y_continuous(breaks = seq(0, 15000, 2500)) +
  geom_text(aes(label = n),hjust = -0.5) +
  coord_flip()->p

p 
```

## add_count

```{r}
iris %>% 
  add_count(Species) %>% 
  select(n,everything())
```

```{r}
ggplot2movies::movies %>% 
  add_count(year) %>% 
  select(n,everything()) %>% 
  head()
```

or:

```{r}
ggplot2movies::movies %>% 
  group_by(year) %>% 
  mutate(n = n()) %>%
  ungroup(year) %>% 
  select(n,everything()) %>% 
  head()
```

## summarise

```{r}
mtcars %>%
  summarise(mean = mean(disp), n = n())

mtcars %>%
  group_by(cyl) %>%
  summarise(mean = mean(disp), n = n())

mtcars %>%
  group_by(cyl, vs) %>%
  summarise(cyl_n = n()) %>%
  ungroup()


mtcars %>%
  group_by(cyl) %>%
  summarise(disp = mean(disp), sd = sd(disp), double_disp = disp * 2)
```

## fct_reorder

```{r}
iris %>% 
  ggplot(aes(fct_reorder(Species,Sepal.Width),Sepal.Width)) +
  geom_boxplot(aes(fill = Species),outlier.fill = "red") +
  labs(x = "Species") +
  theme(text = element_text(family = "Times New Roman",size = 15))
```

## fct_lump

```{r}
x <- factor(rep(LETTERS[1:9], times = c(40, 10, 5, 27, 1, 1, 1, 1, 1)))
x %>% table()
x %>% fct_lump_n(3) %>% table()
x %>% fct_lump_prop(0.10) %>% table()
x %>% fct_lump_min(5) %>% table()
x %>% fct_lump_lowfreq() %>% table()

x <- factor(letters[rpois(100, 5)])
x
table(x)
table(fct_lump_lowfreq(x))

# Use positive values to collapse the rarest
fct_lump_n(x, n = 3)
fct_lump_prop(x, prop = 0.1)

# Use negative values to collapse the most common
fct_lump_n(x, n = -3)
fct_lump_prop(x, prop = -0.1)
```

## scale_x/y_log10

```{r}
library(patchwork)
p1 <- ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  theme(text = element_text(family = "Times New Roman"))
  
p1

# Manipulating the default position scales lets you:* change the axis labels
p1 +
  scale_x_continuous("Engine displacement (L)") +
  scale_y_continuous("Highway MPG")->p2

p1 + p2
```

```{r}
#  * modify the axis limits
p1 + scale_x_continuous(limits = c(2, 6))->p3
p1 + scale_x_continuous(limits = c(0, 10))->p4

p3 + p4

#  * choose your own labels
p1 + scale_x_continuous(
  breaks = c(2, 4, 6),
  label = c("two", "four", "six")
)
```

```{r}
# You can also override the default linear mapping by using a transformation. There are three shortcuts:
p1 + scale_y_log10()-> p1
p1 + scale_y_sqrt()-> p2
p1 + scale_y_reverse() -> p3

# Or you can supply a transformation in the `trans` argument:
p1 + scale_y_continuous(trans = scales::reciprocal_trans())-> p4

# You can also create your own. See ?scales::trans_new

(p1 + p2) / (p3 + p4)
```

## crossing

```{r}
expand(mtcars, vs, cyl)

# Only combinations of vs and cyl that appear in the data
expand(mtcars, nesting(vs, cyl))
```

```{r}
# Implicit missings -----------------------------------------------------
df <- tibble(
  year   = c(2010, 2010, 2010, 2010, 2012, 2012, 2012),
  qtr    = c(   1,    2,    3,    4,    1,    2,    3),
  return = rnorm(7)
)
df

df %>% expand(year, qtr)

df %>% expand(year = 2010:2012, qtr)
df %>% expand(year = full_seq(year, 1), qtr)
df %>% complete(year = full_seq(year, 1), qtr)
```

```{r}
# Nesting -------------------------------------------------------------

experiment <- tibble(
  name = rep(c("Alex", "Robert", "Sam"), c(3, 2, 1)),
  trt  = rep(c("a", "b", "a"), c(3, 2, 1)),
  rep = c(1, 2, 3, 1, 2, 1),
  measurement_1 = runif(6),
  measurement_2 = runif(6)
)
experiment

```

```{r}
# We can figure out the complete set of data with expand()
# Each person only gets one treatment, so we nest name and trt together:
all <- experiment %>% 
  expand(nesting(name, trt), rep)
all
```

```{r}
# We can use anti_join to figure out which observations are missing
all %>% anti_join(experiment)

# And use right_join to add in the appropriate missing values to the original data
experiment %>% right_join(all)
# Or use the complete() short-hand
experiment %>% complete(nesting(name, trt), rep)
```

```{r}
# Generate all combinations with expand():
formulas <- list(
  formula1 = Sepal.Length ~ Sepal.Width,
  formula2 = Sepal.Length ~ Sepal.Width + Petal.Width,
  formula3 = Sepal.Length ~ Sepal.Width + Petal.Width + Petal.Length
)
data <- split(iris, iris$Species)
crossing(formula = formulas, data)
```

## separate

```{r}
df <- data.frame(x = c(NA, "a.b", "a.d", "b.c"))
df
df %>% separate(x, c("A", "B"),sep = "\\.")
```

```{r}
df <- data.frame(x = c("a", "a b", "a b c", NA))
df
df %>% separate(x, c("a", "b"),sep = " ")
# The same behaviour drops the c but no warnings
```

```{r}
df %>% separate(x, c("a", "b"), extra = "drop", fill = "right")
# Another option:
df %>% separate(x, c("a", "b"), extra = "merge", fill = "left")
# Or you can keep all three
df %>% separate(x, c("a", "b", "c"))
```

```{r}
# If only want to split specified number of times use extra = "merge"
df <- data.frame(x = c("x: 123", "y: error: 7"))
df
df %>% separate(x,c("key", "value"), ": ", extra = "merge")
df %>% separate(x,c("key","value"),": ")
```

```{r}
# Use regular expressions to separate on multiple characters:
df <- data.frame(x = c(NA, "a?b", "a.d", "b:c"))
df
df %>% separate(x, c("A","B"), sep = "([\\.\\?\\:])")
```

```{r}
# convert = TRUE detects column classes
df <- data.frame(x = c("a:1", "a:2", "c:4", "d", NA))
df
df %>% separate(x, c("key","value"), ":") 
df %>% separate(x, c("key","value"), ":", convert = TRUE)

# Argument col can take quasiquotation to work with strings
var <- "x"
df %>% separate(!!var, c("key","value"), ":")
```

## extract

```{r}
df <- data.frame(x = c(NA, "ahjjk-knb", "anjk-njkd", "hjbjb-cjbj", "njd-nnke"))
df
df %>% extract(x, "A")
df %>% 
  separate(col = x,into = c("key","value"),sep = "-")
```

```{r}
df %>% extract(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")

# If no match, NA:
df %>% extract(x, c("A", "B"), "([a-z]+)-([a-n]+)")
```