--- 
title: "Tidyr包笔记"
# subtitle: "Lecture title"
author:
- affiliation: Dongbei University of Finance & Economics
  name: Studennt. LI Junjie
date: '`r Sys.Date()`'
output:
  bookdown::html_document2:
    # code_folding: hide
    highlight: pygments
    # highlight: zenburn
    # highlight: haddock
    theme: darkly
    # theme: journal
    df_print: tibble	
    number_sections: true
    keep_md: no
    keep_tex: no
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
      smooth_scroll: yes
    # css: styles.css
# bibliography: [book.bib, packages.bib]
# biblio-style: apalike
link-citations: yes
sansfont: Times New Roman
always_allow_html: yes
urlcolor: "red"
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
editor_options: 
  chunk_output_type: console
---

# 加载经常用的R包


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.show = "hold",
                      fig.align = "center",
                      tidy = FALSE,
                      class.source = "bg-warning")
```

```{js, echo=FALSE}
$('.title').css('color', 'red')
$('.title').css('font-family', 'Times New Roman')
```

```{css, echo=FALSE}
body {
    font-size: 17px !important;
    font-family: "Times New Roman" !important;
    color: rgb(199 237	204)
}
::selection {
   # background: rgb(135 206 255);
}
```

```{r,warning=FALSE,message=FALSE}
library(pacman)
# 读数据
p_load(readxl,writexl,data.table,openxlsx,haven,rvest)
```

```{r,warning=FALSE,message=FALSE}
# 数据探索
p_load(tidyverse,DT,skimr,DataExplorer,explore,vtable,stringr,kableExtra,lubridate)
```

```{r,eval=FALSE,warning=FALSE,message=FALSE}
# 模型
p_load(grf,glmnet,caret,tidytext,fpp2,forecast,car,tseries,hdm,tidymodels,broom)
```

```{r,eval=FALSE,warning=FALSE,message=FALSE}
# 可视化
p_load(patchwork,ggrepel,ggcorrplot,gghighlight,ggthemes,shiny)
```

```{r,eval=TRUE,warning=FALSE,message=FALSE}
# 其它常用包
p_load(magrittr,listviewer,devtools,here,janitor,reticulate,jsonlite)
```

# pivot_longer函数

```{r}
relig_income %>% 
  pivot_longer(cols = -religion)
```

```{r}
billboard %>% 
  pivot_longer(cols = starts_with("wk"),
               names_to = "week",
               names_prefix = "wk")
```

# 列表列

```{r}
iris %>% 
  nest(-Species) %>% 
  .[["data"]]
```

# 拆分

```{r}
df <- data.frame(x = c(NA, "a.b", "a.d", "b.c"))
df
df %>% separate(col = x,into = c("A","B"),sep = "\\.")
df %>% separate(col = x,into = c(NA,"B"),sep = "\\.")
```

```{r}
df %>% separate(col = x,into = c("A","B"),sep = "[.]")
```

# 缺失值处理

```{r}
library(dplyr, warn.conflicts = FALSE)
df <- tibble(
  group = c(1:2, 1),
  item_id = c(1:2, 2),
  item_name = c("a", "b", "b"),
  value1 = 1:3,
  value2 = 4:6
)
df 
```

```{r}
df %>% 
  complete(group,nesting(item_id,item_name)) # 2 * 2
df %>% complete(group, nesting(item_id, item_name), fill = list(value1 = 0))
```

```{r}
df %>% drop_na()
```

```{r}
fruits <- tibble(
  type   = c("apple", "orange", "apple", "orange", "orange", "orange"),
  year   = c(2010, 2010, 2012, 2010, 2010, 2012),
  size  =  factor(
    c("XS", "S",  "M", "S", "S", "M"),
    levels = c("XS", "S", "M", "L")
  ),
  weights = rnorm(6, as.numeric(size) + 2)
)
fruits
fruits %>% expand(type,year)
```

```{r}
# 找出没有重复值的行
iris %>% 
  expand(nesting(Sepal.Length,Sepal.Width,Petal.Width,Petal.Length))
```

```{r}
expand_grid(x = 1:3,y = 2:5)
expand_grid(l1 = letters, l2 = LETTERS)
```






























