---
title: "janitor包——检查和清理脏数据"
author: "ljj"
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: espresso
    theme: united
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 5
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.show = "hold",
                      fig.align = "center",
                      tidy = FALSE)
```

## 加载经常用的R包

```{r,warning=FALSE,message=FALSE}
library(pacman)
p_load(tidyverse,stringr,DT,skimr,DataExplorer,grf,glmnet,caret,tidytext,
       explore,patchwork,ggrepel,ggcorrplot,gghighlight,ggthemes,fpp2,
       forecast,magrittr,readxl,writexl,listviewer,car,tseries,vtable)
```

```{r}
iris %>% 
  janitor::clean_names() %>% 
  as_tibble()
```

```{r}
iris %>% 
  n_distinct()  # 149
```

```{r}
iris %>% 
  janitor::get_dupes()  # 有两行一模一样！！！
```

```{r}
iris %>% 
  janitor::get_dupes(contains("Species"))
```

```{r}
iris %>% 
  janitor::tabyl(Species)
```

```{r}
mtcars %>% 
  janitor::tabyl(cyl,vs)
```

```{r}
mtcars %>% 
  janitor::tabyl(cyl,vs,gear)
```
















