---
title: "R爬虫完整教程"
# subtitle: "Lecture title"
author:
- affiliation: Dongbei University of Finance & Economics
  name: Studennt. LJJ
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    highlight: haddock
    keep_md: no
    keep_tex: no
    theme: flatly
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
      smooth_scroll: yes
mainfont: Times New Roman
monofont: Times New Roman
left:
- href: index.html
  text: Home
- href: other.html
  text: Other
right:
- href: https://github.com
  text: GitHub
sansfont: Times New Roman
always_allow_html: yes
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

## 加载经常用的R包

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.show = "hold",
                      fig.align = "center",
                      tidy = FALSE,
                      class.source = "bg-warning")
```

```{r,warning=FALSE,message=FALSE}
library(pacman)
# 读数据
p_load(readxl,writexl,data.table,openxlsx,haven,rvest)
```

```{r,warning=FALSE,message=FALSE}
# 数据探索
p_load(tidyverse,DT,skimr,DataExplorer,explore,vtable,stringr,lubridate)
```

```{r,eval=FALSE,warning=FALSE,message=FALSE}
# 模型
p_load(grf,glmnet,caret,tidytext,fpp2,forecast,car,tseries,hdm,tidymodels,broom)
```

```{r,eval=FALSE,warning=FALSE,message=FALSE}
# 可视化
p_load(patchwork,ggrepel,ggcorrplot,gghighlight,ggthemes,shiny)
```

```{r,eval=FALSE,warning=FALSE,message=FALSE}
# 其它常用包
p_load(magrittr,listviewer,devtools,here,janitor,reticulate,jsonlite)
```

## 基本函数

- read_html()，用于读取网页，语法如下。

```md
read_html(x, encoding = "", ..., options = c("RECOVER", "NOERROR", "NOBLANKS"))

# x为网址链接
# encoding = #解码 UTF-8
```

- html_nodes()，定位并读取节点信息，语法如下。

```md
html_nodes(x, css, xpath)
# css与 xpath 路径二选一即可
# css路径表示为：div.show-detail p.house-title a
# xpath路径表示为：xpath= "//p[@class='house-title']//a
```

- html_text()，从数据中抽离出文本。

```md
html_text(x, trim = FALSE)
# trim选择是否去掉空格
```

- html_attr()，从数据中抽离属性值。

```md
html_attr(x)
```

## 分析网页结构

西域网的特种扳手品类：

- http://www.ehsy.com/category-16883
- http://www.ehsy.com/category-16883?p=2
- http://www.ehsy.com/category-16883?p=3

基本确定http://www.ehsy.com/category-16883?p=i的格式即为最后的格式!

## 读取网页

### 读取第一个网页（测试）

```{r}
url <- 'http://www.ehsy.com/category-16883?p=1'
web <- read_html(url,encoding = "UTF-8")
web
```

```{r}
name <- web %>% 
  html_nodes(".p-name .high-light") %>% 
  html_text()

sku <-  web %>% 
  html_nodes(".product-parameter .high-light") %>% 
  html_text(trim = TRUE)

price <- web %>% html_nodes(".yen") %>% 
  html_text(trim = TRUE) %>% 
  .[seq(2,72,2)]
  
stock <- web %>% 
  html_nodes(".stock") %>% 
  html_text()

df <- tibble(name,price,stock,sku)

guess_encoding(stock)
repair_encoding(stock)
```

### 爬取整个页面

```{r}
tictoc::tic()
map(1:20, function(i) {
  url <- str_c('http://www.ehsy.com/category-16883?p=', i, sep = "")
  web <- read_html(url)
  name <- web %>%
    html_nodes(".p-name .high-light") %>%
    html_text()
  
  sku <-  web %>%
    html_nodes(".product-parameter .high-light") %>%
    html_text(trim = TRUE)
  
  price <- web %>% html_nodes(".yen") %>%
    html_text(trim = TRUE) %>%
    .[seq(2, 72, 2)]
  
  stock <- web %>%
    html_nodes(".stock") %>%
    html_text()
  
  df <- tibble(name, price, stock, sku)
  return(df)
}) %>% 
  bind_rows()-> data
tictoc::toc()
```

15.39 sec elapsed

## 并行运算：看看那个函数更快











