---
title: "Tushare"
author: "ljj"
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: espresso
    theme: united
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 5
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.show = "hold",
                      fig.align = "center",
                      tidy = FALSE)
```

## 加载经常用的R包

```{r,warning=FALSE,message=FALSE}
library(pacman)
p_load(tidyverse,stringr,DT,skimr,DataExplorer,grf,glmnet,caret,tidytext,
       explore,patchwork,ggrepel,ggcorrplot,gghighlight,ggthemes,fpp2,
       forecast,magrittr,readxl,writexl,listviewer,car,tseries,vtable)
```

```{r}
pro <- Tushare::pro_api(token = '4563b71d2582929f061585a3b075a0bbca4a1ee1c6616259ef668fde')
```

## 得到305家公司

```{r}
pro(api_name = 'stock_basic')->data
data %>% 
  filter(area == "深圳") %>% 
  select(ts_code) %>% 
  pull() -> ts_code

ts_code %>% length()
```

```{r}
bar <- Tushare::pro_bar(token = '4563b71d2582929f061585a3b075a0bbca4a1ee1c6616259ef668fde')
```

## 一个公司

```{r}
bar(
  ts_code = "000001.SZ",
  start_date = "20181001",
  adj = "hfq",
  ma = c(5, 10)
) %>% 
  as_tibble()
```

## 305家公司数据

```{r}

```


















