---
title: "读书总结"
author: "LJJ"
date: "2020/4/9"
output: html_document
---

读书习惯：学习筛选后需要认真阅读的书籍，至少阅读两遍，第一遍是未知的学习和探索，第二遍是回顾和回味，总结不懂的知识，忘记已经掌握的知识，孰能生巧，让书中的知识由文字转化为流水，流进心田，融会贯通。不要担心阅读后忘记，阅读不在于背诵，甚至不在于记忆，而在于理解，在于消化，在于思考，知其所以然，这本书给自己最深刻的影响何在，无论是技术文档，还是小说，作者这么写一定有他的考虑，虽然书不一定都对，发现错误也是一种阅读的收获。但切忌读过的书成为吃过的饭，喝过的水，走过的路，哈哈。

---

## Learn Rstudio IDE

该书不需要入门读，而是入门后读，别有一番收获，对R有系统的了解和认知，R(Rsudio)原来可以做这么多事情！！！

---

## R数据科学

主要讲述了使用R进行数据科学的流程，构建了数据分析的框架，看完这本书，基本可以完成日常80%的数据处理工作，感谢RStudio团队无私奉献的开源产品！！！从数据导入、数据清洗、数据可视化、数据探索、R初级编程、建模和沟通等方面介绍了一系列R包，也可以说是利剑，自己学过的包括不限于以下几个包：

R包            |        描述
-------------  |  -------------
readr          |   读入csv数据
haven          |   读入其它类型数据集(stata、SPSS和SAS)
readxl         |   读入Excel数据
dplyr          |   整理数据，核心六个函数
tidyr          |   数据重构，核心两个函数  
ggplot2        |   数据可视化，有许多基于该包的扩展包
explore        |   数据探索
skimr          |   数据描述
DT             |   数据展示
furrr          |   并行处理
modelr         |   建立模型，模型输出更加干净
caret          |   机器学习包，该作者正在重构tidymodel
knitr          |   Sweave的替代工具，具有更灵活的设计和新功能
blogdown       |   建立网站
rmarkdown      |   写文档和代码

---

## Data Manipulation in R

该书主要以代码为主，详细介绍了若干数据处理包，作者是一位数据科学家，敲完这本书的代码并认真回顾，别有一番收获。

---

## 萧十一郎和火并萧十一郎

---

## 遥远的救世主

---

## 大学

---

## 中庸

---

## 孟子

---

## 论语

---

## 背叛

---

## 人生十讲






















